language: python
python:
  - 2.7
  - 3.6
sudo: false
install:
  - pip install tox-travis
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install --lts
  - nvm use --lts
  - npm install
script:
  - tox
cache:
  directories:
    - ~/.cache/pip
    - ~/.nvm/
